export const SELECT_CATEGORY = "SELECT_CATEGORT";
export const SELECT_DIFFICULTY = "SELECT_DIFFICULTY";
export const SELECT_QUESTION_AMOUNT = "SELECT_QUESTION_AMOUNT";
export const SELECT_QUESTION_TYPE = "SELECT_QUESTION_TYPE";
export const CHANGE_SCORE = "CHNAGE_SCORE";